name: payload

on: push

jobs:
  App:
    name: payload
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include: [
          { PACKAGE: 'UefiPayloadPkg', PACKAGE_DSC: 'UefiPayloadPkg.dsc', TARGET: 'RELEASE', ARCH: 'IA32_X64', TOOLCHAIN: 'GCC5',       ADDITIONAL_DEFINITION: '-D BOOTLOADER=COREBOOT -D PS2_KEYBOARD_ENABLE=TRUE -D SIO_BUS_ENABLE=TRUE' },
          { PACKAGE: 'UefiPayloadPkg', PACKAGE_DSC: 'UefiPayloadPkg.dsc', TARGET: 'DEBUG',   ARCH: 'IA32_X64', TOOLCHAIN: 'GCC5',       ADDITIONAL_DEFINITION: '-D BOOTLOADER=COREBOOT -D PS2_KEYBOARD_ENABLE=TRUE -D SIO_BUS_ENABLE=TRUE' },
        ]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup build environment
        run: |-
          sudo apt-get update
          sudo apt-get install -y nasm acpica-tools build-essential uuid-dev python3.8 python3-distutils python3-pip bc gawk
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          sudo update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 10
      - name: Setup edk2 build environment
        run: |-
          if [ ! -d "BaseTools/Source/C/bin" ]; then
            make -C BaseTools
          fi
          pushd $PWD && cd BaseTools/Source/C/GenBin & make && popd
          cp BaseTools/BinWrappers/PosixLike/GenCrc32 BaseTools/BinWrappers/PosixLike/GenBin
          chmod a+x BaseTools/BinWrappers/PosixLike/GenBin
          cd CryptoPkg/Library/OpensslLib/
          perl process_files.pl
      - name: Build
        run: |-
          if [ "${{ matrix.ARCH }}" = "IA32" ]; then
            export ARCH_STR='-a IA32'
          fi
          if [ "${{ matrix.ARCH }}" = "X64" ]; then
            export ARCH_STR='-a X64'
          fi
          if [ "${{ matrix.ARCH }}" = "AARCH64" ]; then
            export ARCH_STR='-a AARCH64'
          fi
          if [ "${{ matrix.ARCH }}" = "IA32_X64" ]; then
            export ARCH_STR='-a IA32 -a X64'
          fi
          source edksetup.sh
          build ${ARCH_STR} -t ${{ matrix.TOOLCHAIN }} -p ${{ matrix.PACKAGE }}/${{ matrix.PACKAGE_DSC }} -b ${{ matrix.TARGET }} ${{ matrix.ADDITIONAL_DEFINITION }}
      - uses: actions/upload-artifact@v2
        with:
          name: COREBOOT_PAYLOAD_${{ github.sha }}_${{ matrix.PACKAGE }}_${{ matrix.TARGET }}_${{ matrix.TOOLCHAIN }}_${{ matrix.ARCH }}
          path: |-
            Build/**/*.efi
            Build/**/FV/*.fd
            Build/BUILDLOG*.*
            Build/CI_*.*
            Build/SETUPLOG.*
            Build/UPDATE*.*
            Build/**/AutoGen.*